Fix MT error: TypeError: key.trim is not a function
Template parameter keys can be integers sometimes. Handle
those cases as well.

The js error was caused by calling trim() function on
numbers.

Bug: T207662
Change-Id: Ia91b9ce65a17efefe9f5e9331039c7fbe5a20abc